export const routs = {
    home: "/home",
    products: "/products",
    productDetails: "/product/",
    contact: "/contact",
    aboutUs: "/about-us",
    login: "/login",
    logout: "/logout",
    register: "/register",
    companyDetails: "/myCompany",
    addCoupon: "/addCoupon",
    manageCoupon: "/manageCoupon/",
    updateCompany: "/company/update",
    customerCoupons: "/customer/coupons",
    adminCompanies: "/admin/companies",
    adminCompanyDetails: "/admin/company/",
    adminUpdateCompany: "/admin/company/update/",
    adminAddCompany: "/admin/company/add",
    adminCustomers: "/admin/customers",
    adminCustomerDetails: "/admin/customer/",
    adminUpdateCustomer: "/admin/customer/update/",
}